### ISSUE TITLE
asdfasdf

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/foo#14]
asdfasdf

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|8b26cc03d9245ff9e2519143c2a5a60ac4c194b7|[culture#L2](https://github.com/reviewninja/foo/blob/8b26cc03d9245ff9e2519143c2a5a60ac4c194b7/culture#L2)| #1 |[![#1](http://localhost:60000/assets/images/icon-alt-36.png)](http://localhost:60000/reviewninja/foo/pull/1)|

**Comment by gruiz17** [comment]
fsdf

**Comment by gruiz17** [comment]
hjkljkljl
