### ISSUE TITLE
blah

### ISSUE THREAD

**Issue by dfarr** [reviewninja/foo#237]
|commit|file reference|pull request|   |
|------|--------------|------------|---|
|9b285ae0b6b974b312ce916b25684190fbc52220|`none`| #236 |[![#236](http://review-ninja-staging.cfapps.io/assets/images/icon-alt-36.png)](http://review-ninja-staging.cfapps.io/reviewninja/foo/pull/236)|

**Comment by fabianschwarzfritz** [comment]
asdfasdf

**Comment by fabianschwarzfritz** [comment]
asdfasdf

**Comment by fabianschwarzfritz** [comment]
asdf
